FROM ubuntu:16.04

ADD https://repo.anaconda.com/miniconda/Miniconda3-py37_4.9.2-Linux-x86_64.sh /opt
ADD https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.centos6_x86_64.tar.bz2 /opt
ADD https://github.com/DecodeGenetics/graphtyper/releases/download/v2.7.1/graphtyper /usr/local/bin

# graphtyper and deps
RUN apt-get update -qq \
    && apt-get -y install --no-install-recommends build-essential bzip2 python2.7 git ca-certificates \
    && chmod a+x /usr/local/bin/graphtyper

WORKDIR /opt
RUN  cp /usr/bin/python2.7 /usr/bin/python2 \
	     && tar xjf manta-1.6.0.centos6_x86_64.tar.bz2 \
	     && rm manta-1.6.0.centos6_x86_64.tar.bz2 \
	     && rm -rf manta-1.6.0.centos6_x86_64/manta-1.6.0.centos6_x86_64/share
ADD configManta.py.ini /opt/manta-1.6.0.centos6_x86_64/bin/
ADD split_by_size.py /usr/local/bin/


ENV PATH=/opt/manta-1.6.0.centos6_x86_64/bin:/opt/manta-1.6.0.centos6_x86_64/libexec/:/opt/:manta-1.6.0.centos6_x86_64/lib/python/:$PATH


## conda + svimmer
WORKDIR /opt
ENV PATH=/opt/miniconda/bin:$PATH
RUN sh Miniconda3-py37_4.9.2-Linux-x86_64.sh -b -p /opt/miniconda/ \
	    && conda install -yc bioconda pysam bcftools && \
	    rm Miniconda3-py37_4.9.2-Linux-x86_64.sh && \
	    git clone https://github.com/DecodeGenetics/svimmer && \
	    cp svimmer/svimmer svimmer/sv.py svimmer/utilities.py /opt/miniconda/bin/ && \
	    svimmer -h

