FROM ubuntu:18.04
MAINTAINER brentp

ARG htslib_version=1.16
ARG tiwih_version=v0.1.6

RUN apt-get -qq update && \
     apt-get -qq install -y --no-install-recommends --no-install-suggests \
     curl wget ca-certificates git-core less netbase unzip \
     g++ cmake autoconf make file \
     libjemalloc-dev libzip-dev libsnappy-dev libbz2-dev zlib1g-dev liblzma-dev libzstd-dev \
     pv

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1

RUN \
    git clone --recursive --depth 1 --branch $htslib_version https://github.com/samtools/htslib && \
    cd htslib && autoheader && autoconf && \
    ./configure && \
    cd .. && make -j4 CFLAGS="-fPIC -O3" -C htslib install && \
    git clone --depth 1 --branch $htslib_version https://github.com/samtools/samtools && \
    cd samtools && autoheader && autoconf && \
    ./configure --without-curses --enable-s3  && \
    make -j4 CFLAGS="-fPIC -O3" install && \
    cd ../ && \
    git clone https://github.com/lh3/bwa.git && \
    cd bwa && make && cp ./bwa /usr/local/bin/ && \
    git clone --depth 1 https://github.com/GregoryFaust/samblaster.git && \
	cd samblaster && \
	make && \
	cp samblaster /usr/local/bin/
   

ADD https://github.com/brentp/tiwih/releases/download/$tiwih_version/tiwih /usr/local/bin

RUN chmod +x /usr/local/bin/tiwih \
