FROM ubuntu:20.04

ARG htslib_version=1.13
#ARG octopus_version=v0.7.4
ARG octopus_version=44cd3f77c1f2e6b7ac41b624cd20475fc750da1e
ARG architecture=nehalem 
# sandybridge


WORKDIR /opt
ADD https://github.com/luntergroup/octopus/archive/${octopus_version}.tar.gz .

RUN apt-get update -qq && apt-get -y --no-install-recommends --no-install-suggests upgrade && \
    apt-get -y install  --no-install-recommends --no-install-suggests software-properties-common && \
    add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update -qq  && apt-get -y upgrade && \
    apt-get -y install --no-install-recommends gcc-10 libgmp3-dev git-all python3 build-essential bzip2 git ca-certificates cmake libboost-all-dev zlib1g-dev autoconf python3-distro libbz2-dev liblzma-dev libcurl4-openssl-dev curl && \
    apt-get autoremove --yes && rm -rf /var/lib/apt/lists/* 

RUN \
    git clone --recursive https://github.com/samtools/htslib && \
    cd htslib && git checkout ${htslib_version} && autoheader && autoconf && \
    ./configure --disable-libcurl --without-libdeflate && \
    make -j4 CFLAGS="-fPIC -O3 -march=${architecture}" install && \
    cd ../ && \
    git clone --recursive https://github.com/samtools/bcftools && \
    cd bcftools && git checkout ${htslib_version} && autoheader && autoconf && \
    ./configure --disable-libcurl --without-libdeflate && \
    make -j4 CFLAGS="-fPIC -O3 -march=${architecture}" install && \
    cd ../ && rm -rf htslib bcftools

ENV CMAKE_BUILD_PARALLEL_LEVEL=5
RUN tar xzvf ${octopus_version}.tar.gz && \
	    cd octopus-*/ && \
	    ./scripts/install.py --forests --prefix=/usr/local/bin --architecture=${architecture} && \
	    rm -f ../${octopus_version}.tar.gz && \
      echo "/usr/local/lib/" >> /etc/ld.so.conf && ldconfig && \
      mv resources/forests/*.forest.gz /opt/ && \
      cd .. && rm -rf octopus* && \
      rm /opt/somatic.v0.7.4.forest.gz

ENV germline_forest=/opt/germline.v0.7.4.forest.gz

