FROM ubuntu:18.04
MAINTAINER brentp

ARG htslib_version=1.16
ARG tiwih_version=v0.1.6

RUN apt-get -qq update && \
     apt-get -qq install -y --no-install-recommends --no-install-suggests \
     curl wget ca-certificates git-core less netbase unzip \
     g++ cmake autoconf make file \
     libjemalloc-dev libzip-dev libsnappy-dev libbz2-dev zlib1g-dev liblzma-dev libzstd-dev \
     pv

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1

RUN  git clone --depth 1 --branch $glnexus_version https://github.com/dnanexus-rnd/GLnexus && \
     cd GLnexus && \
     cmake -DCMAKE_BUILD_TYPE=Release . && make -j8 &&  \
     mv /GLnexus/glnexus_cli /usr/local/bin && \
     rm -rf /GLnexus

RUN \
    git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && make -j 2 CFLAGS='-fPIC -O3' libdeflate.a && \
    cp libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include && \
    cd .. && rm -rf libdeflate && \
    git clone --recursive --depth 1 --branch $htslib_version https://github.com/samtools/htslib && \
    cd htslib && autoheader && autoconf && \
    ./configure --with-libdeflate && \
    cd .. && make -j4 CFLAGS="-fPIC -O3" -C htslib install && \
    git clone --depth 1 --branch $htslib_version https://github.com/samtools/samtools && \
    cd samtools && autoheader && autoconf && \
    ./configure --without-curses --enable-s3 --with-libdeflate && \
    make -j4 CFLAGS="-fPIC -O3" install && \
    cd ../ && \
    git clone https://github.com/lh3/bwa.git && \
    cd bwa && make && cp ./bwa /usr/local/bin/ && \
    git clone git://github.com/GregoryFaust/samblaster.git && \
	cd samblaster && \
	make && \
	cp samblaster /usr/local/bin/
   

ADD https://github.com/brentp/tiwih/releases/download/$tiwih_version/tiwih /usr/local/bin

RUN chmod +x /usr/local/bin/tiwih \
